language: scala
scala:
  - 2.10.3
jdk:
  - oraclejdk7

before_install:
- sudo apt-get update
- sudo apt-get install agda-bin
- sudo apt-get install coq

sbt_args: -J-Xms512M -J-Xmx1500M -J-Xss2M -XX:MaxPermSize=724M

script: sbt ++$TRAVIS_SCALA_VERSION test it:test
